### ISSUE TITLE
Sinks: when sink is created, status should be "new" as the agents, instead of "unknown"

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#584]
This is required to keep a unique pattern between sinks and agent status:

![image](https://user-images.githubusercontent.com/78241475/179307353-b14c437a-9f56-40de-b687-627b7c6a31c0.png)

![image](https://user-images.githubusercontent.com/78241475/179307412-18f1e1d8-8977-4ecb-b757-667156360581.png)

**Comment by lpegoraro** [comment]
This can be also changed with the Notification Service, we are planning to create

But if this need to be implemented before, it can be achieved with the following implementation
This became a bit more tricky because of Otel implementation
I guess, we can support this in Otel version, since we plan to deprecate the non-otel sinks

TODOs
- [ ] Add handleSinksCreateCollector in maestro/redis/consumer/ a call to an event stream orb.sinker.update with the New state
OR 
- [ ] In sinks creation, send two events, one orb.sinks.create and an orb.sinker.update with the new state.

But if this is not necessary, I would wait until the development of the Notification Central.
